type = "service_account"
project_id = "fancy-project-name-c09f0"
private_key_id = "bedc48465068f8098c79a43a6ef3569a3a3ff780"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsS2fNBFb+85wy
qUBe5HHvBx/EV1u/8p0K/xM8tTBfGsmq8qOwDkM1NANp856hGR9h9t98VJj03piJ
+3UWuc5yy2aIKXgMfo+1BC/6Aj/CNJiqCbVxx3yW1cMoISFbF3EfYErdVRg6l9s/
/xHOrrcThM+8UnBbTrvFrBLnG+wVpAz4Fp215V5vKfLk83nTjf1vrkCVMnZrHaX2
P8Y1U4EDmSNB5n8JqZX3RsycZaRKCGVCWZu9ShxZBx7LCsHBAJMYslRN7iUh0/NE
cCb8ZDL/BhDwo4Pr56ICQcH4CKp7CIDPXiYYbS8lEqI82GDVqLS3i+CFelJNoYZN
I05vecL3AgMBAAECggEAK2os08peKYw1NcbUQ5UI6JRA+vaQVgPKcrTnogp+D9ju
LDdL69cMNGHQ4mfS9wEfmU3d7rRafomAonRMgtd7IA4E3hak+3EAwTo25Kagbk1W
krIzmGIOEOv4ayo9/3getytKcg85NbqCMtQRJqV72F1FA006pqdmRV8gvD+a87Ci
T3od7AYTbgZiEuqY0vjwiOWZ5tJ7ptICQNMZgXNU+9S8vg5zr5loHhQ5gdRTTFu2
x75Dz+lhOoL5rCSJo4TigGJW56xFQfX7Om3vJCVALqXmJ+QZK/zR39HF6hPXW8ow
dK9ZBzc/rMm4RYeBU+A516b512n63DbGjCy0r9mWEQKBgQDru1KVsJxqyTKZ4jdH
O9ZtGU6Sx9SV3hQjPp21mET4J/w3MmjIQVzsLcakglWbFBhQXA+5lC1xKPA2W/gs
ko53W92txpkrBlK3w01Kmv1JgAsuM5A6JINPGUVWWvBSsxF9HESiOxKpDwmw/pQK
BlciPfmS4DHcb+xFV8X8tS7j2wKBgQC7G8VXwsAbzALRUSo0LjbP1gvM/FTwzs1I
wgeJLfTbR4rOkDtucwWDcXGnN6Se4ywmVQy4La6eKvh9e9fNc+rmTE3bLFkWCdgm
MsVj9bAjca2UjLx15W9VGfpQ89kafe8ymFikyDxP4/kNSFDSB4E6zCdJDQ5iu8uY
h68YLPjWFQKBgH0eexIKoKspSVtWL6L2hrR3hzXvLM2zBxtB4/F79beFeaBOeEE6
ODj/fvzYVNmwC8uzYYFNveTfJsijfhEiZM3Di+DtlWS5wXPaDI85vpChjs2h/r5t
nOiB8ESKlh4+/1xZgbBeDGSBH9K6/RZpERySqoIjzzNCkLSphuO/wzibAoGAbZtE
DDf6f44P7HxGY9DarP9vZEJAo9wRJ1j6PyLbuAR9zKlzFy1sAmbXNCSFW8oqF75k
uBOSofb8H84HScRoy0XRqd2dxio4I5BET10iNHEoRMf4snuXr1uLZhaijEFPeO0D
qGvf4NDkGSLOrWpWCpKDROjQD4iBKLX7HQdjMU0CgYBOUBuw3BZfZeGWOdyu7nx7
hYJvnDJ/AETyFz7G5Go2CmhDVOUqunpWDULcGTF0dakO4ei1IX/IOwfmqzLGT/pc
zCq7UuS9GnMhCUA1eTxi1LwZGcSL2wxcFy0/Hk+01Ijka8NkbP4Hvq7/QSEjeZ0o
v+D3RQBct3EMx+CE90TZ9g==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-t7j6x@fancy-project-name-c09f0.iam.gserviceaccount.com"
client_id = "112140749474155562269"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-t7j6x%40fancy-project-name-c09f0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
